### ISSUE TITLE
Getting back user from token on request

### ISSUE THREAD

**Issue by HiImMilanxd** [bratkartoffel/security-jwt#34]
Hi there, is there any way of getting back JwtUser (so I can get users username and perform action in their name) on request when using `@Secured` annotation?

**Comment by bratkartoffel** [comment]
Hi,

sure, although it doesn't work with `@Secured`, you can use the more advanced `@PreAuthorized` annotation to do so.
I've created an example to show you how to do so:

https://github.com/bratkartoffel/security-jwt-examples/commit/692da806cf39ecd97aa5c3e41b94a8fbd234c186

**Comment by HiImMilanxd** [comment]
Hi there, 
thanks for the response, I really appreciate it, but is there any way of getting the username as a variabile or argument for function?

**Comment by bratkartoffel** [comment]
Hi there,

you can inject the Principal to your controller or access the `SecurityContextHolder` directly. A nice tutorial about how to do this is written on baeldungs site: https://www.baeldung.com/get-user-in-spring-security

**Comment by HiImMilanxd** [comment]
Thank you so much this is exactly what I needed!
